### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by Ingore** [haoyuhu/cluster-analysis#1]
您好：
我运行显示 NameError: name 'xrange' is not defined ，
请问是这是指数据的维度么？要怎么定义？
谢谢！

**Comment by haoyuhu** [comment]
`xrange`只能在Python2.7里使用，如果你是用的Python3，需要对代码做一些修改。比如`xrange`改为`range`。REF: https://www.geeksforgeeks.org/range-vs-xrange-python/

**Comment by Ingore** [comment]
懂了，感谢！

**Comment by haoyuhu** [comment]
Closing the issue since this is not likely a bug.
